// SPDX-License-Identifier: (GPL-2.0-only OR BSD-2-Clause)

#ifndef _DT_BINDINGS_SPACEMIT_K3_POWER_H_
#define _DT_BINDINGS_SPACEMIT_K3_POWER_H_

#define K3_PMDOMAIN_VPU		0
#define K3_PMDOMAIN_GPU		1
#define K3_PMDOMAIN_AUDIO	2
#define K3_PMDOMAIN_LCD0	3
#define K3_PMDOMAIN_LCD1	4

#endif /* _DT_BINDINGS_SPACEMIT_K3_POWER_H_ */
