/* SPDX-License-Identifier: (GPL-2.0-only OR BSD-2-Clause) */

#ifndef _DT_BINDINGS_SPACEMIT_K1_POWER_H_
#define _DT_BINDINGS_SPACEMIT_K1_POWER_H_

#define K1_PMDOMAIN_VPU		0
#define K1_PMDOMAIN_GPU		1
#define K1_PMDOMAIN_LCD		2
#define K1_PMDOMAIN_ISP		3
#define K1_PMDOMAIN_AUDIO	4
#define K1_PMDOMAIN_GNSS	5
#define K1_PMDOMAIN_HDMI	6

#endif // _DT_BINDINGS_SPACEMIT_K1_POWER_H_
